### ISSUE TITLE
using this function for zipping csv

### ISSUE THREAD

**Issue by mehdipourfar** [pramsey/pgsql-gzip#1]
Hi, I use this command for generating csv.
COPY (SELECT * FROM my_table) TO STDOUT WITH (FORMAT ZIP, HEADER, DELIMITER E'\t');

I want to know if I can use this pakage to zip my content before sending it to application

**Comment by pramsey** [comment]
Yes, but you'll have to aggregate your output so it's a single piece of text before you feed it into gzip, which means forming the whole CSV in the SQL rather than letting the CSV format in COPY do it for you automatically.

Something like
```sql
SELECT gzip(string_agg(concat(col1, E'\t', col2, E'\t', col3), E'\n'))
FROM mytable
```

Depending on your system access and how you're running the command, you might find something like 
```
COPY SELECT * FROM my_table) TO PROGRAM 'gzip > /tmp/file.csv.gz' 
  WITH (FORMAT csv, HEADER, DELIMITER E'\t');
```
is easier and closer to what you want
